DROP TABLE order_details;
DROP TABLE order_order;
DROP TABLE dish_ver;
DROP TABLE dish;
DROP TABLE token;
DROP TABLE user_user;
DROP TABLE restaurant_info;
DROP TABLE restaurant_hour;
DROP TABLE restaurant;